--- 
abstract: Inheritable, overridable class and instance data accessor creation
author: Based on the creative stylings of Damian Conway, Michael G Schwern,
distribution_type: module
generated_by: Module::Install version 0.65
license: artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Data-Accessor
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  perl: 5.6.1
tests: t/*.t t/*/*.t
version: 0.04001
